<?php

/**
 * @var $form \Image\Form\ImageForm
 */

$this->headTitle('Add Image');


$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-primary');

$form->prepare();

?>

<h1>Add Image</h1>

<hr>

<?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?= $this->formLabel($form->get('image')); ?>
    <br>
    <?= $this->formFile($form->get('image')); ?>
    <?= $this->formElementErrors($form->get('image')); ?>
</div>
<br>
<div class="form-group">
    <?= $this->formElement($submit); ?>
</div>

<?= $this->form()->closeTag() ?>
